name = "formatio"
version = "0.1.0"
license = "license"
author = "Jiří Fürst"
maintainer = "Jiri.Furst@gmail.com"
copyright = "Copyright 2023, Jiří Fürst"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

